#Импорты
from aiogram import executor
from config.bot_config import dp
from handlers.admin_panel.create_post.create_post import *
from handlers.admin_panel.create_post.states_post.post_name import *
from handlers.admin_panel.create_post.states_post.post_user import *
from handlers.admin_panel.create_post.states_post.post_text import *
from handlers.admin_panel.create_post.states_post.post_photo import *
from handlers.admin_panel.create_post.states_post.post_lvl import *
from handlers.admin_panel.main_menu import *
from handlers.start.start import *
from handlers.admin_panel.create_user_role.create_user_role import *
from handlers.admin_panel.create_user_role.admin.admin import *
from handlers.admin_panel.create_user_role.cm.cm import *
from handlers.admin_panel.delete_user_role.delete_user_role import *
from handlers.admin_panel.change_post.show_post import *
from handlers.admin_panel.change_post.states_change_post.post_id import *
from handlers.admin_panel.change_post.states_change_post.post_name import *
from handlers.admin_panel.change_post.states_change_post.post_list import *
from handlers.admin_panel.change_post.states_change_post.post_text import *
from handlers.admin_panel.change_post.states_change_post.post_photo import *
from handlers.user_panel.create_user import *
from handlers.test.start_test import *
from handlers.test.questions.q1 import *
from handlers.test.questions.q2 import *
from handlers.test.questions.q3 import *
from handlers.test.questions.q4 import *
from handlers.test.questions.q5 import *
from handlers.test.questions.q6 import *
from handlers.test.questions.q7 import *
from handlers.test.questions.q8 import *
from handlers.test.questions.q9 import *
from handlers.test.questions.q10 import *
from handlers.test.questions.q11 import *
from handlers.test.questions.q12 import *
from handlers.test.questions.q13 import *
from handlers.test.questions.q14 import *
from handlers.test.questions.q15 import *
from handlers.test.questions.q16 import *
from handlers.test.questions.q17 import *
from handlers.test.questions.q18 import *
from handlers.test.questions.q19 import *
from handlers.test.questions.q20 import *
from handlers.test.questions.q21 import *
from handlers.test.questions.q22 import *
from handlers.test.questions.q23 import *
from handlers.test.questions.q24 import *
from handlers.test.questions.q25 import *
from handlers.test.questions.q26 import *
from handlers.test.questions.q27 import *
from handlers.test.questions.q28 import *
from handlers.test.questions.q29 import *
from handlers.test.questions.q30 import *
from handlers.user_panel.main_menu import *
from handlers.user_panel.user_profile.show_user_profile import*
from handlers.test.start_second_test import *
from handlers.user_panel.materials.post_list import *
from handlers.user_panel.materials.post_id import *
from handlers.admin_panel.create_test.show_post import *
from handlers.admin_panel.create_test.post_name import *
from handlers.admin_panel.create_test.post_id import *
from handlers.admin_panel.create_test.post_list import *
from handlers.admin_panel.create_post.states_post.post_writing import *
from handlers.admin_panel.change_post.states_change_post.post_writing import *
from handlers.writing.writing import *
from handlers.writing.essay.show import *
from handlers.writing.essay.essay import *
from handlers.writing.essay.show_resut import *
from handlers.test.skip_test import *
from handlers.user_panel.user_profile.settings import *
from handlers.user_panel.user_profile.subscribe import *
from handlers.user_panel.day_function import *


if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=True) 
    